In [105]:
a=10
print(a)

10


In [106]:
import numpy as np
a=np.array([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [107]:
arr=np.arange(2,20)
element=arr[6]
print (element)

8


In [108]:
arr_slice=slice(1,10,2)
element=arr[6]
print (element)
print (arr_slice)
print (arr[arr_slice])

8
slice(1, 10, 2)
[ 3  5  7  9 11]


In [109]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])
print (a[0:2,0:2])
print (a.shape)
print (a.ndim)
print (a.itemsize)
x=np.empty([3,2],dtype=int)
print (x)

[[1 2]
 [2 3]]
(3L, 3L)
2
4
[[2 3]
 [4 3]
 [4 5]]


In [110]:
a=np.array([[2,3,4],[3,4,5]])
print (a)
print (a.itemsize)
print (a.shape)
print (a.ndim)
print (a.ravel())
print (a)
element_single=a.ravel()
print (element_single)

[[2 3 4]
 [3 4 5]]
4
(2L, 3L)
2
[2 3 4 3 4 5]
[[2 3 4]
 [3 4 5]]
[2 3 4 3 4 5]
